# Generated by Django 4.0b1 on 2021-11-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'Cluster',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=10000)),
                ('depth', models.IntegerField(max_length=100)),
                ('crawling_strategy', models.CharField(choices=[('ALL', 'ALL'), ('DOC', 'DOC'), ('PDF', 'PDF'), ('PPT', 'PPT'), ('XML', 'XML')], max_length=100)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Urls', to='cluster.cluster')),
            ],
            options={
                'db_table': 'URL',
            },
        ),
    ]
