# Generated by Django 4.0b1 on 2021-11-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_alter_url_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='depth',
            field=models.CharField(max_length=10000),
        ),
    ]
