# Generated by Django 3.2.6 on 2021-11-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_cluster_crawled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='crawled',
            field=models.BooleanField(default=False),
        ),
    ]
