# Generated by Django 3.2.6 on 2021-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_alter_cluster_crawled'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileurl', models.CharField(max_length=10000)),
                ('fileType', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=100000000000000000)),
            ],
            options={
                'db_table': 'File',
            },
        ),
    ]
