# Generated by Django 3.2.6 on 2021-11-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='fileType',
            new_name='filetype',
        ),
    ]
