# Generated by Django 3.2.6 on 2021-12-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0008_alter_url_crawling_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mainUrl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Urls', to='cluster.url'),
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.TextField(max_length=100000000000000000),
        ),
    ]
