# Generated by Django 3.2.6 on 2021-12-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0009_auto_20211204_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='mainUrl',
            new_name='mainurl',
        ),
    ]
