# Generated by Django 3.2.6 on 2021-12-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0010_rename_mainurl_file_mainurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.CharField(max_length=100000000000000000),
        ),
    ]
