# Generated by Django 3.2.6 on 2021-12-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0011_alter_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.TextField(max_length=100000000000000000),
        ),
    ]
