# Generated by Django 3.2.6 on 2021-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0014_alter_file_mainurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filecluster',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
